
name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t silvertetris/densitydata:latest .
    - name: Tag the Docker image
      run: docker tag silvertetris/densitydata:latest silvertetris/densitydata:latest
    - name: Push the Docker image
      run: docker push silvertetris/densitydata:latest
